lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import StudentsView, FriendsAPI, FriendListView, FriendDetailView

urlpatterns = [
        url(r'^$', StudentsView.as_view(), name='index'),
        url(r'^students$', StudentsView.as_view(), name='students'),
        url(r'^students/page/(?P<page>[0-9]+)/', StudentsView.as_view(), name='students-page'),
        url(r'^friends$', FriendsAPI.as_view(), name='friends'),
        url(r'^friends/npm/(?P<npm>[0-9X-Z]+)/', FriendsAPI.as_view(), name='friends-npm'),
        url(r'^friend-list', FriendListView.as_view(), name="friend-list"),
        url(r'^friend-detail/(?P<npm>[0-9X-Z]+)', FriendDetailView.as_view(), name='friends-detail'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from lab_1.views import index as index_lab1
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^$', RedirectView.as_view(url='lab-4/', permanent='true'), name='index'),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10'))
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    added_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name + ', ' + self.npm

lab_7/views/friend_detail.py
import json
from django.shortcuts import render, HttpResponse
from django.views.generic.base import TemplateView
from django.core import serializers

from lab_7.models import Friend
from lab_7.api_cs_ui_helper import CSUIhelper

AUTHOR = 'Yudhistira Erlandinata'

class FriendDetailView(TemplateView):
    template_name = 'lab_7/detail_teman.html'

    def get(self, request, npm=None, *args, **kwargs):
        query = Friend.objects.filter(npm=npm)
        if query:
            struct = json.loads(serializers.serialize('json', query))
            friend = struct[0]['fields']
            data_csui = CSUIhelper().instance.get_mahasiswa(npm)
            if data_csui:
                friend['address'] = data_csui['alamat_mhs']
                friend['city'] = data_csui['kota_lahir']
                friend['birth_date'] = data_csui['tgl_lahir']
                friend['major'] = data_csui['program'][0]['nm_org'] + ' ' + data_csui['program'][0]['nm_prg'] 
            response = {'friend' : friend, 'author' : AUTHOR}
            return render(request, FriendDetailView.template_name, response)
        else:
            return HttpResponse(status=404)

lab_7/views/friend_list.py
import json
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.core import serializers

from lab_7.models import Friend

AUTHOR = 'Yudhistira Erlandinata'

class FriendListView(TemplateView):
    
    template_name = 'lab_7/daftar_teman.html'

    def get(self, request, page=1, *args, **kwargs):
        data = serializers.serialize('json', Friend.objects.all())
        friends = json.loads(data)
        friends = [f['fields'] for f in friends]
        response = {"friend_list": friends, "author": AUTHOR}
        return render(request, FriendListView.template_name, response)

lab_7/views/friends.py
import os
import json
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.core import serializers
from django.db.utils import IntegrityError

from lab_7.models import Friend

class FriendsAPI(TemplateView):

    def get(self, request, npm=None, *args, **kwargs):
        if npm:
            query = Friend.objects.filter(npm=npm)
            if query:
                struct = json.loads(serializers.serialize('json', query))
                data = json.dumps(struct[0]['fields'])
                return JsonResponse(data, safe=False)
            else:
                return HttpResponse(status=404)
        data = serializers.serialize('json', Friend.objects.all())
        struct = json.loads(data)
        data = json.dumps([d['fields'] for d in struct])
        return JsonResponse(data, safe=False)

    def post(self, request, *args, **kwargs):
        name = request.POST['name']
        npm = request.POST['npm']
        friend = Friend(name=name, npm=npm)
        if Friend.objects.filter(npm=npm):
            return HttpResponseBadRequest('{"error": "Mahasiswa sudah ada"}')
        friend.save()
        return HttpResponse(status=201)

    def delete(self, request, npm=None, *args, **kwargs):
        if npm is None:
            return HttpResponseBadRequest()
        query = Friend.objects.filter(npm=npm)
        if query:
            query[0].delete()
            return HttpResponse()
        else:
            return HttpResponse(status=404)

lab_7/views/students.py
import json
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.core import serializers

from lab_7.models import Friend
from lab_7.api_cs_ui_helper import CSUIhelper

AUTHOR = 'Yudhistira Erlandinata'
MAX_PAGE = 68

class StudentsView(TemplateView):

    template_name = 'lab_7/lab_7.html'

    def get(self, request, page=1, *args, **kwargs):
        page = int(page)
        if page < 1 or page > MAX_PAGE: # max page 68
            page = 1
        data = serializers.serialize('json', Friend.objects.all())
        friends = json.loads(data)
        friends = [f['fields'] for f in friends]
        mahasiswa_list = CSUIhelper().instance.get_mahasiswa_list(page)
        npm_list = [friend['npm'] for friend in friends]
        response = {"mahasiswa_list": mahasiswa_list, "friend_list": friends, 
            "author": AUTHOR, "npm_list": npm_list, "page":page, "max_page":MAX_PAGE, "next_page": page+1, "prev_page": page-1}
        return render(request, StudentsView.template_name, response)
    

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
<section name="friend-list" id="friend-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Friend Fasilkom</h2>
                <div id="friend-list" class="list-group">

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>

    $( document ).ready(function () {
        $.ajax({
            method: "GET",
            url: "{% url 'lab-7:friends' %}",
            success: function (response) {
                response = JSON.parse(response)
                for(var i = 0; i < response.length; i++) {
                    console.log(response[i])
                    const element = $('<span class="list-group-item clearfix" href="' + '/lab-7/friend-detail/' + response[i].npm + '/" >' + 
                            '<a href="' + '/lab-7/friend-detail/' + response[i].npm + '/">' + response[i].name + ' (' + response[i].npm + ')</a>' + 
                            '</span>')
                    $('.list-group').append(element)

                    const delButton = $('<span class="pull-right">' +
                                        '<span class="btn btn-xs btn-danger" id="'+ response[i].npm +'">' +
                                        'Hapus pertemanan' + 
                                        '</span></span>') 
                    delButton.hide()
                    element.append(delButton)
                                        
                    element.mouseenter(function(){
                        delButton.show('fast')
                    })
                                        
                    element.mouseleave(function(){
                        delButton.hide('fast')
                    })

                    const npm = response[i].npm

                    delButton.click(function(){

                        console.log(delButton)

                        $.ajax({
                            method: 'DELETE',
                            url: '/lab-7/friends/npm/' + npm + '/',
                            beforeSend: function(xhr) {
                                xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                            },
                            success: function(){
                                element.hide('slow')
                            },
                            error: function(error){
                                console.log(error)
                            }
                        })

                    })

                }
            },
            error: function(error){
                console.log(error)
            }
        });

       
    });


</script>
{% endblock %}

lab_7/templates/lab_7/detail_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
<section name="friend-detail">
    <div class="container">
        <div class="page-header">
            <h2>{{ friend.name }}</h2>
        </div>
        <div class="col-md-8 col-xs-12">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-5 col-xs-4">NPM</div>
                    <div class="col-md-7 col-xs-8">{{ friend.npm }}</div>
                </div>
                {% if friend.address %}
                <div class="row">
                    <div class="col-md-5 col-xs-4">Jurusan</div>
                    <div class="col-md-7 col-xs-8">{{ friend.major }}</div>
                </div>
                <div class="row">
                    <div class="col-md-5 col-xs-4">Alamat</div>
                    <div class="col-md-7 col-xs-8">{{ friend.address }}</div>
                </div>
                <div class="row">
                    <div class="col-md-5 col-xs-4">Tempat, tanggal lahir</div>
                    <div class="col-md-7 col-xs-8">{{ friend.city }}, {{ friend.birth_date }}</div>
                </div>
                
                {% endif %}
            </div>
            <br />
        </div>
        <div class="col-md-4 col-xs-12">
            <div id="map"></div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBlrXmjMGK7g6BmgsM2Yo-WYG_5v8viNc4&callback=initMap"> </script>
<script>

    var address = 'Fakultas Ilmu Komputer Universitas Indonesia'

    {% if friend.address %}
    address = '{{ friend.address }}'
    {% endif%}

    function initMap() {
        console.log('address: ' + address)
        $.ajax({
            method: 'GET',
            url: 'https://maps.googleapis.com/maps/api/geocode/json',
            data: {
                address: address,
                key: 'AIzaSyBlrXmjMGK7g6BmgsM2Yo-WYG_5v8viNc4'
            },
            success: function(response){
                console.log(response)
                const loc = {
                    lat: parseInt(response.results[0].geometry.location.lat), 
                    lng: parseInt(response.results[0].geometry.location.lng)
                };
                console.log(loc)
                const map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 7,
                    center: loc
                });
                const marker = new google.maps.Marker({
                    position: loc,
                    map: map
                });
            },
            error: function(error){

            }
        })

    }
</script>

{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                {% include "lab_7/partials/pagination.html" %}
                <div class="list-group hide-first">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                                    {% if mahasiswa.npm not in npm_list %}
                                    <span class="btn btn-xs btn-default" id="student-{{ mahasiswa.npm }}" onClick="addFriendButton(this.id, '{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                                            Tambah sebagai teman
                                    </span>
                                    {% else %}
                                    <span class="btn btn-xs btn-info disabled">
                                            Teman
                                    </span>
                                    {% endif %}
                                </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
                {% include "lab_7/partials/pagination.html" %}
            </div>
            <div class="col-md-8 col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center " id="nofriend">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <div class="lab-form form-group">
                    <label for="field_npm">NPM</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">Nama</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="button" class="btn" id="add-friend">Tambah</button>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>

    const page = '{{page}}'
    var timeOut;

    const addFriendButton = function(buttonId, nama, npm){
        const addButton = $('#' + buttonId)
        addButton.hide('normal')
        const container = addButton.parent()
        const friendButton = $('<span class="btn btn-xs btn-info disabled"> Teman </span>')
        friendButton.hide()
        container.append(friendButton)
        friendButton.show('slow')
        addFriend(nama, npm)
    };

    const addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:friends" %}',
            data: { 
                name: nama, 
                npm: npm,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success : function (friend) {
                console.log(friend)
                const html = '<a class="list-group-item clearfix">' +
                    nama + '(' + npm +')' +
                    '</a>';
                const newItem = $(html)
                console.log(html)
                $("#friend-list").append(newItem)
                newItem.hide()
                newItem.show('slow')
                $("#field_name").val('')
                $("#field_npm").val('')
                $('#nofriend').hide('fast')
            },
            error : function (error) {
                console.log(error)
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    const alreadyFriend = function(){

    }

    $("#add-friend").click(function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
       console.log(name)
       console.log(npm)
        addFriend(name, npm)
    });

    $(".next-page").click(function(){
        collapse()
    })

    $(".prev-page").click(function(){
        collapse()
    })

    const collapse = function(){
        $('.hide-first').hide('slow')
        scrollToTop()
    };

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "GET",
            url: '/lab-7/friends/npm/' + npm + '/',
            dataType: 'json',
            success: function (data) {
                console.log(data)
                alert("Mahasiswa dengan npm ini sudah ada")
                $("#field_npm").select()
            }
        });
    });

$(document).ready(function(){
    $('.hide-first').show('normal')
    if (page == 1) $('.prev-page').hide()
    if (page == 68) $('.next-page').hide()
});

function scrollToTop() {
	if (document.body.scrollTop!=0 || document.documentElement.scrollTop!=0){
		window.scrollBy(0,-50);
		timeOut=setTimeout('scrollToTop()',30);
	}
	else clearTimeout(timeOut);
}

</script>
{% endblock %}